# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Documentation HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
        python -m pip install matplotlib furo m2r2 sphinx
    - name: Build Document
      working-directory: doc/
      run: make html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc/_build/html/ # The folder the action should deploy.
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: DocumentationHTML
    #    path: doc/_build/html/
